<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('products')->insert([
            [
                'product_id' => 1,
                'category_id' => 8,
                'name' => 'Lavender Essential Oil',
                'description' => 'Calming yet aromatic Lavender essense. Best for sleep.',
                'price' => 75000,
                'stock' => 50,
                'image_url' => 'lavenderscentedcandle.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 2,
                'category_id' => 1,
                'name' => 'Vanilla Scented Candle',
                'description' => 'Sweet and alluring aroma of vanilla.',
                'price' => 80000,
                'stock' => 45,
                'image_url' => 'vanillascentedcandle.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 3,
                'category_id' => 3,
                'name' => 'Purple Wax Melt',
                'description' => 'All purpose purple wax and save for skin.',
                'price' => 25000,
                'stock' => 100,
                'image_url' => 'purplewaxmelt.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 4,
                'category_id' => 4,
                'name' => 'Rose Decorative Candle',
                'description' => 'Rose molded candle with neutral scented candle.',
                'price' => 30000,
                'stock' => 80,
                'image_url' => 'rosedecorativecandle.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 5,
                'category_id' => 3,
                'name' => 'Flake Soy Wax Melt',
                'description' => 'Easier to melt soy based wax.',
                'price' => 45000,
                'stock' => 60,
                'image_url' => 'flakesoywaxmelt.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 6,
                'category_id' => 2,
                'name' => 'Clay Pot Accessories',
                'description' => '3.5inch clay based pot for your candles.',
                'price' => 50000,
                'stock' => 70,
                'image_url' => 'claypotcandleaccessory.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 7,
                'category_id' => 5,
                'name' => 'Lavender Bath Bomb',
                'description' => 'Lavender scented bath bomb infused with vitamins.',
                'price' => 40000,
                'stock' => 65,
                'image_url' => 'lavenderbathbomb.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 8,
                'category_id' => 5,
                'name' => 'Eucalyptus Bath Bomb',
                'description' => 'Homemade eucalyptus bath bombs perfect for at-home wellness.',
                'price' => 60000,
                'stock' => 90,
                'image_url' => 'eucalyptusbathbomb.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 9,
                'category_id' => 7,
                'name' => 'Snowball Seasonal Candle',
                'description' => 'Snowball shaped unscented candle.',
                'price' => 85000,
                'stock' => 40,
                'image_url' => 'snowballseasonalcandle.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 10,
                'category_id' => 8,
                'name' => 'Lemon Essential Oil',
                'description' => 'Refreshing scent lemon essential oils.',
                'price' => 62000,
                'stock' => 95,
                'image_url' => 'lemonessentialoil.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 11,
                'category_id' => 9,
                'name' => 'Pink Candle Making Kit',
                'description' => 'Fun activities for family to make candle at home.',
                'price' => 150000,
                'stock' => 30,
                'image_url' => 'pinkcandlemaking.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 12,
                'category_id' => 7,
                'name' => 'Autumn Seasonal Candle',
                'description' => 'Pinecone and pumpkin scented candle.',
                'price' => 120000,
                'stock' => 25,
                'image_url' => 'autumncandle.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 13,
                'category_id' => 11,
                'name' => 'White Unscented Candle',
                'description' => 'Long endurance white unscented candle.',
                'price' => 35000,
                'stock' => 75,
                'image_url' => 'whiteunscentedcandle.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 14,
                'category_id' => 12,
                'name' => 'Lavender Soap',
                'description' => 'Handmade soap with lavender scent.',
                'price' => 45000,
                'stock' => 85,
                'image_url' => 'lavendersoap.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 15,
                'category_id' => 13,
                'name' => 'Rose Crush Aromatherapy',
                'description' => 'Rose Scented Aromatherapy.',
                'price' => 180000,
                'stock' => 20,
                'image_url' => 'rosearomatherapy.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 16,
                'category_id' => 1,
                'name' => 'Amber Forest Candle',
                'description' => 'Warm earthy scent inspired by woodland walks.',
                'price' => 89000,
                'stock' => 45,
                'image_url' => 'amberforest.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 17,
                'category_id' => 8,
                'name' => 'Eucalyptus Essential Oil',
                'description' => 'Crisp scent perfect for breathing relief.',
                'price' => 72000,
                'stock' => 60,
                'image_url' => 'eucalyptusoil.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 18,
                'category_id' => 5,
                'name' => 'Coconut Milk Bath Bomb',
                'description' => 'Creamy fizz with hydrating coconut oil.',
                'price' => 46000,
                'stock' => 38,
                'image_url' => 'coconutmilkbathbomb.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 19,
                'category_id' => 7,
                'name' => 'Spring Blossom Candle',
                'description' => 'Fresh floral blend perfect for springtime.',
                'price' => 99000,
                'stock' => 20,
                'image_url' => 'springblossomcandle.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 20,
                'category_id' => 1,
                'name' => 'Forest Pine Candle',
                'description' => 'Invigorating pine fragrance for nature lovers.',
                'price' => 86000,
                'stock' => 37,
                'image_url' => 'forestpine.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 21,
                'category_id' => 8,
                'name' => 'Bergamot Essential Oil',
                'description' => 'Bright citrus scent to elevate mood.',
                'price' => 70000,
                'stock' => 58,
                'image_url' => 'bergamotoil.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 22,
                'category_id' => 5,
                'name' => 'Lemongrass Spa Bomb',
                'description' => 'Uplifting citrus fizz for spa vibes.',
                'price' => 44000,
                'stock' => 41,
                'image_url' => 'lemongrassbomb.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 23,
                'category_id' => 1,
                'name' => 'Jasmine Night Candle',
                'description' => 'Romantic jasmine scent for evening calm.',
                'price' => 91000,
                'stock' => 36,
                'image_url' => 'jasminenight.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 24,
                'category_id' => 1,
                'name' => 'Mint Chill Candle',
                'description' => 'Refreshing mint to cool the atmosphere.',
                'price' => 84000,
                'stock' => 42,
                'image_url' => 'mintchillcandle.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 25,
                'category_id' => 7,
                'name' => 'Autumn Spice Candle',
                'description' => 'Cinnamon, clove & nutmeg for fall coziness.',
                'price' => 95000,
                'stock' => 28,
                'image_url' => 'autumnspice.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 26,
                'category_id' => 5,
                'name' => 'Lavender Milk Bath Bomb',
                'description' => 'Gentle fizz with milk protein and lavender.',
                'price' => 48000,
                'stock' => 32,
                'image_url' => 'lavendermilkbathbomb.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 27,
                'category_id' => 8,
                'name' => 'Tea Tree Essential Oil',
                'description' => 'Purifying scent with herbal undertones.',
                'price' => 65000,
                'stock' => 50,
                'image_url' => 'teatreeoil.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 28,
                'category_id' => 1,
                'name' => 'Honey & Fig Candle',
                'description' => 'Sweet scent of ripened fig with warm honey.',
                'price' => 88000,
                'stock' => 34,
                'image_url' => 'honeyfigcandle.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 29,
                'category_id' => 7,
                'name' => 'Winter Cabin Candle',
                'description' => 'Smoky cedar and vanilla for a wintry vibe.',
                'price' => 98000,
                'stock' => 22,
                'image_url' => 'wintercabin.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 30,
                'category_id' => 5,
                'name' => 'Mint Eucalyptus Bomb',
                'description' => 'Energizing combo of mint and eucalyptus oils.',
                'price' => 47000,
                'stock' => 43,
                'image_url' => 'minteucalyptusbathbomb.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 31,
                'category_id' => 8,
                'name' => 'Lavender Essential Oil',
                'description' => 'Classic calming oil for sleep and balance.',
                'price' => 69000,
                'stock' => 65,
                'image_url' => 'lavenderoil.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
            [
                'product_id' => 32,
                'category_id' => 7,
                'name' => 'Valentine Rose Candle',
                'description' => 'Soft rose petals with a hint of musk.',
                'price' => 97000,
                'stock' => 26,
                'image_url' => 'valentinerose.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
                'status_del' => 0,
            ],
        ]);
    }
}
